<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.samancore</groupId>
        <artifactId>workflow</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>workflow-json-diagram</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <workflow.version>1.0.0-SNAPSHOT</workflow.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.samancore</groupId>
            <artifactId>workflow-model</artifactId>
            <version>${workflow.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-core</artifactId>
        </dependency>
    </dependencies>

</project>
